=== srnabab/zig_game/schema/sampler.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "sampler.schema.json",
  "title": "Vulkan Sampler (.samp) Config",
  "type": "object",
  "properties": {
    "flags": {
      "type": "integer"
    },
    "magFilter": {
      "type": "integer"
    },
    "minFilter": {
      "type": "integer"
    },
    "mipmapMode": {
      "type": "integer"
    },
    "addressModeU": {
      "type": "integer"
    },
    "addressModeV": {
      "type": "integer"
    },
    "addressModeW": {
      "type": "integer"
    },
    "mipLodBias": {
      "type": "number"
    },
    "anisotropyEnable": {
      "type": "boolean"
    },
    "maxAnisotropy": {
      "type": "number"
    },
    "compareEnable": {
      "type": "boolean"
    },
    "compareOp": {
      "type": "integer"
    },
    "minLod": {
      "type": "number"
    },
    "maxLod": {
      "type": "number"
    },
    "borderColor": {
      "type": "integer"
    },
    "unnormalizedCoordinates": {
      "type": "boolean"
    }
  }
}

=== srnabab/zig_game/Sampler/pixel2dSampler.json
{
  "flags": 0,
  "magFilter": 0,
  "minFilter": 0,
  "mipmapMode": 0,
  "addressModeU": 0,
  "addressModeV": 0,
  "addressModeW": 0,
  "mipLodBias": 0.0,
  "anisotropyEnable": true,
  "maxAnisotropy": 1.0,
  "compareEnable": false,
  "compareOp": 0,
  "minLod": 0.0,
  "maxLod": 0.0,
  "borderColor": 1,
  "unnormalizedCoordinates": false
}
